### ISSUE TITLE
Confused about env setting for the tasks

### ISSUE THREAD

**Issue by aphecetche** [FairRootGroup/DDS#163]
Hi,

I guess there is one (at least ;-)) I do not quite understand in the topology definition. 

I'm using the ssh plugin on a few "virtual" hosts (that are docker containers in fact...). All the hosts have the O2 stack installed (possibly several stacks in fact), so the executable for my tasks are on the target systems ... somewhere. 

Conceptually what I need to execute on the worker nodes is :  "alienv enter O2/version && my task --id ... --config ... --control ..." 

How am I supposed to do that ? With <env> ? Specifying a local or a remote script ?

Thanks for any clarification,

**Comment by AnarManafov** [comment]
I would defiantly wrap the command into a script. Then do what is the most convenient for you, either put that script on your worker nodes somewhere or leave it own the DDS server machine.
When you define a Tasks in the topology (using "decltask") you have an option to specify whether the executable of your task is reachable from the WN or not. If you specify "false", then DDS will take your script and upload it on each WN before executing the task. Otherwise it will assume the executable is available on the worker nodes by the path you provided.

See for more info: http://dds.gsi.de/doc/nightly/topology.html#topology-section1

Feel free to reopen if you have any question in this regard.
