### ISSUE TITLE
non daemon dds-server ?

### ISSUE THREAD

**Issue by aphecetche** [FairRootGroup/DDS#164]
I'd like to have a dds-server in a docker container. 
The thing is that the first process of a container must not return, i.e. it can't be a daemon. 
I've tried to use dds-commander directly, but then I miss a few goodies set up by the dds-server (e.g. the server directory hierarchy creation...)

Would you consider adding a --no-daemon option to the server ? Or is there already a way to achieve this ? 

Thanks,

**Comment by AnarManafov** [comment]
I am not sure about --no-daemon. I mean, it is doable, but honestly I don't see a reason for it at the moment. By design commander should run as a daemon.
The idea of DDS is to provide a toolset, which then can be wrapped up to create a higher level tools or machineries.

How about the following workaround for your issue.
You can create a shell script - a wrapper, which calls "dds-server start" and then waits in a loop until commander is done or for other events your might need. In the loop you can simply constantly check for "ddd-server status" and for other conditions if needed.

We use a similar approach in our automated tests. In the code snippet below we wait until the server is up. In your case the conditions should be exactly opposite. The loop also watches for a defined time out in order to avoid endlessly lopping.

~~~~~~~
echo "waiting for commander server to start..."
dds-server status $> /dev/null
COUNT=0
# max 10 sec.
MAX_COUNT=100
while [ $? -ne 0 ]; do
	if [ $COUNT -gt $MAX_COUNT ]; then
		echo "Error: Timeout is reached."
		clean_up 1
	fi
	sleep 0.1
	COUNT=$(expr $COUNT + 1)
	dds-server status $> /dev/null
done
dds-server status
~~~~~~~

This will still allow you to run the commander as designed as a daemon and also make your first process (your wrapper shell script) to stay as long as needed.

Feel free to reopen if this workaround doesn't resolve the issue.
