### ISSUE TITLE
Error while building DDS 1.6

### ISSUE THREAD

**Issue by ktf** [FairRootGroup/DDS#175]
We recently moved from DDS 1.4 to DDS 1.6 in the AliceO2 builds but while it works on some platforms (e.g. my local mac installation), on some other (e.g. the Centos7 setup we use to check PR) we get:

```
-- Using BOOST Library dir: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.64.0-alice1_O2_DAQ-1/lib
-- prerequisite dirs: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.64.0-alice1_O2_DAQ-1/lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-user-defaults;/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-protocol-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-intercom-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-topology-lib;/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/MiscCommon/dds_ncf
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-intercom-lib/libdds_intercom_lib.so'
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-protocol-lib/libdds_protocol_lib.so'
WN PKG prerequisite='/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/dds-user-defaults/libdds-user-defaults.so'
WN PKG prerequisite='/usr/lib/libgcc_s.so.1'
-- 
warning: cannot resolve item 'libstdc++.so.6'

  possible problems:
    need more directories?
    need to use InstallRequiredSystemLibraries?
    run in install tree instead of build tree?

WN PKG prerequisite='libstdc++.so.6'
CMake Error at /mnt/mesos/sandbox/sandbox/sw/SOURCES/DDS/master-1.6/1.6/cmake/modules/DDS_CollectPrerequisites.cmake:33 (file):
  file COPY cannot find
  "/mnt/mesos/sandbox/sandbox/sw/BUILD/747bb7726bb3ef819448b35cc34fd52e9c4f7a6f/DDS/libstdc++.so.6".


make[3]: *** [CMakeFiles/wn_bin] Error 1
make[2]: *** [CMakeFiles/wn_bin.dir/all] Error 2
make[1]: *** [CMakeFiles/wn_bin.dir/rule] Error 2
make: *** [wn_bin] Error 2
``` 

I suspect this is due to the fact that we build our own GCC, rather than using the system one (because the system one is too old to compile AliceO2). How can I trick the new logic to find out the correct GCC?

**Comment by AnarManafov** [comment]
Can you please attach the full came log and output?
Also, what is the full path of the custom gcc you use?

**Comment by ktf** [comment]
Full log is at:

[fullLog.txt](https://github.com/FairRootGroup/DDS/files/1227553/fullLog.txt)

Installation path for GCC is:

/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v6.2.0-alice1-2/

which is correctly reported by DDS initial `cmake` run.

**Comment by AnarManafov** [comment]
in order to unblock you, please remove building of worker packages from your installation.
You are building DDS 1.6. For this version of DDS we provide worker packages. They will be automatically used by DDS at runtime.
So, just remove the "wn_bin" target from your build commands.

In meantime, I will try to reproduce your environment and find a workaround. It will take some time.

**Comment by ktf** [comment]
Ok, will try that. Do you provide WN packages also for OSX?

**Comment by AnarManafov** [comment]
Yes, we do.
So, please try that. I don't want you to be blocked while we are investigating this case.

**Comment by AnarManafov** [comment]
Giulio, can you please confirm what is exact path to libstdc++.so.6 (the one which comes with the custom gcc) on your system?

**Comment by AnarManafov** [comment]
Due to macos's SIP we can't use system's (DY)LD_LIBRARY_PATH and I didn't find any other way to retrieve the location of the stdc++ library of the custom gcc.
Boost libs probably also don't have the full path to stdc++, this is why our script tried to use the build directory patch as the library path for stdc++.

As a workaround, we introduced a new env variable (DDS_LD_LIBRARY_PATH), which users can use to specify custom locations for their libraries (like in case of a custom installation of a compiler).

But most users won't  need it, as it only needed for builds of beta versions of DDS with a custom gcc installations.
