### ISSUE TITLE
Excessive CPU usage of dds-commander on agent disconnect

### ISSUE THREAD

**Issue by dennisklein** [FairRootGroup/DDS#268]
When 3840 tasks terminate and thus the agents are about to disconnect, I observe excessive CPU usage of `dds-commander` process for a period of ~30 seconds after the `.term` command in the `sample-client` has returned already:

![dds-commander-cpu](https://user-images.githubusercontent.com/297548/65900303-fcb7cb00-e3b5-11e9-828b-4571c0760547.jpeg)

Red CPU usage here means kernel space.

**Comment by AnarManafov** [comment]
This is an expected behaviour.
DDS sends TASK_DONE commands to all tasks via Intercom channels (API). It is ~3K commands to each task. 

At the moment it kinda blindly sends, whenever user task is finished.
But it makes sense to skip sending this command if the whole topology is stopped.
I guess, it's a minor issues, but we will teach DDS about handling such cases smarter.

**Comment by AnarManafov** [comment]
Should be fixed in the master.
Instead of sending this message to all task slots, the commander sends it to agents only.
For 3K tasks, there will be not (3K*3K) messages, but only (3K*<number of agents>) messages.
