### ISSUE TITLE
Installing DDS without symlinks to boost libraries

### ISSUE THREAD

**Issue by awegrzyn** [FairRootGroup/DDS#357]
Dear DDS developers,
Is it possible to install DDS without having symlinks  to `libboost_*`? 
Eg. in `/home/alibuild/sw/slc7_x86-64/DDS/3.5.10-1/lib` I get:
```
lrwxrwxrwx. 1 alibuild alibuild      75 Mar 12 09:32 libboost_atomic.so.1.75.0 -> /home/alibuild/sw/slc7_x86-64/boost/v1.75.0-1/lib/libboost_atomic.so.1.75.0
lrwxrwxrwx. 1 alibuild alibuild      75 Mar 12 09:32 libboost_chrono.so.1.75.0 -> /home/alibuild/sw/slc7_x86-64/boost/v1.75.0-1/lib/libboost_chrono.so.1.75.0
...
```

**Comment by AnarManafov** [comment]
Hey @awegrzyn ,

at the moment the links are always created. There is no an off switch.
In the past we experienced multiple cases when users compiled DDS with one BOOST version, but then used another at runtime. BOOST is an essential part of DDS and mixing versions at runtime might result in unpredictable behaviour.
Sometime also users forget to add boost lib path to the runtime environment.
Therefore we had to add an additional protection to make sure DDS uses the version it was build against without forcing the user to export it.

Are those soft links a source of any kind problems?
Could you please enlighten a bit more on this one?
So that we can get a picture of your use case.

**Comment by awegrzyn** [comment]
Thanks for prompt response,
On FLPs we want to to install entire O2 software stack under single directory structure (`include/`, `lib/`,...) therefore the symlinks are conflicting with actual boost libraries. In order to avoid that we've been deleting them in `alidist` recipe: https://github.com/alisw/alidist/blob/9cc138cea67451f02986c259b24313923b2653b6/dds.sh#L43

With new DDS and boost the above delete command stopped working. We can simply adapt it and keep it as it was but it'd would be more clean to have a CMake option on DDS side.

It's just nice to have request, I leave it for your judgment.

**Comment by AnarManafov** [comment]
Got you.
I will look into adding a CMake option. 
Can't promise to get it ready fast, as we have at the moment a higher priority tasks. But I will for sure push this task to the dev queue.

**Comment by dennisklein** [comment]
related to #199

**Comment by AnarManafov** [comment]
Added: A cmake option "CREATE_BOOST_SYMLINKS", which enables creation of boost (libboost_*) symlinks in $DDS_LOCATION/lib/. Default is OFF. (GH-199, GH-357)
