### ISSUE TITLE
[codemeta] 4 Fields required by OSSR are missing

### ISSUE THREAD

**Issue by kresan** [FairRootGroup/DDS#475]
Results of codemeta-validator:

"Missing 4 required keys: ['**softwareVersion**' '**author**' '**maintainer**' '**readme**']"

**Comment by ChristianTackeGSI** [comment]
See also https://github.com/FairRootGroup/DDS/pull/474#issuecomment-1664026433

**Comment by ChristianTackeGSI** [comment]
Just to put it also here:

@AnarManafov if you need help with those fields, let us know.

**Comment by AnarManafov** [comment]
Fixed.
Thank you!

**Comment by ChristianTackeGSI** [comment]
According to [Github Contributors](https://github.com/FairRootGroup/DDS/graphs/contributors) DDS has more authors/contributors than just the [three ones currently in codemeta](https://github.com/FairRootGroup/DDS/blob/4961dfe0a2f782764a1eea3e79be825710522e55/codemeta.json#L15-L32)

Note: We ARE required to add proper data to codemeta.

**Comment by AnarManafov** [comment]
@ChristianTackeGSI , the data provided in codemeta is proper. All required fields are provided and are true.
I don't think we should be duplicating the data, which can be easily retrieved from github GUI or API. 
Boom:
```bash
git shortlog --summary --numbered --email
```

Authors is a specific subject and not possible to automatically retrieve. This is why it is a part of the meta info of the project. 
But a contributors list - is very easy to get using git commands or github GUI/API. 
I don't think, duplication of information is the way to go. Otherwise it will turn into a bureaucracy project, rather than a catalog helper.
