### ISSUE TITLE
Topology hash check fails

### ISSUE THREAD

**Issue by rbx** [FairRootGroup/DDS#480]
With DDS 3.9, when I do update command in ODC, I get:
```
24/24 Error [1073302945173030897]: Topology hash check failed: 2840462574 (must be 1109741260)
```
I also set `m_disableValidation = true` in the request.

In the update indeed I am launching a different topology file - the one I want to update the execution with, and not the old one.

 A bug?

**Comment by AnarManafov** [comment]
@rbx , can be a bug, I have to investigate. 3.9 passed internal tests, where we also test topo update commands.
This is not a topology validation issue, so m_disableValidation has no effect here.

The problem is the agent, which sent this error, has a different topology registered not the one being activated.
Do you get this error from all agents or just some of them?

**Comment by rbx** [comment]
I get it once from the API call. Not sure how to check per agent or not.

**Comment by AnarManafov** [comment]
Try to make a clean start. And repeat your steps. If you get the error, let me know.
Also, please, if possible attach the log either from all agents or only from the one which got this error.
And the log file from your commander.

If this is not really doable atm. At least let me know whether you get this error constantly or time to time.

I will double check on this issue in anyway.
